import { fisherYates,keyOf,normalizeDisplay,normalizePos } from './utils.js';
export function adaptiveStage(state,item){const k=keyOf(item.word),c=state.srs[k],a=state.adaptive[k],w=state.wrong[k]||0;if(w>=2||a?.lastResult==='wrong')return'weak';if(!c&&!(state.seen[k]>0))return'new';const b=c?.box||0;if(b<=1)return'learning';if(b<=3)return'remembering';return'strong';}
export const adaptiveStageText=s=>({new:'Mới',learning:'Đang học',remembering:'Đang nhớ',strong:'Gần thuộc',weak:'Từ yếu'})[s]||'Adaptive';
function rate(state,item,mode){const r=state.adaptive[keyOf(item.word)]?.byMode?.[mode];if(!r)return null;const n=(r.c||0)+(r.w||0);return n?(r.c||0)/n:null;}
export function chooseAdaptiveMode(state,item,index=0,forced='adaptive',kind='smart'){if(kind!=='smart'&&forced!=='adaptive')return forced;const s=adaptiveStage(state,item),last=state.adaptive[keyOf(item.word)]?.lastMode||'';if(s==='new')return'envi';if(s==='weak')return last==='envi'?'vien':'envi';if(s==='learning')return last==='vien'?'envi':'vien';if(s==='remembering'){const r=rate(state,item,'listen');if(r===null||r<.8)return'listen';return index%2?'vien':'listen';}const tr=rate(state,item,'type');return tr===null||tr>=.6?'type':'listen';}
const ppos=p=>normalizePos(p).split(',')[0].trim();const shared=(a,b)=>{const s=new Set(a.topics||[]);return(b.topics||[]).some(t=>s.has(t));};const display=(x,m)=>m==='vien'?String(x.word||''):String(x.meaning||'');
export function selectDistractors(item,vocab,mode='envi',count=3,rng=Math.random){const tw=keyOf(item.word),td=normalizeDisplay(display(item,mode)),seenW=new Set(),c=[];for(const x of vocab){const wk=keyOf(x.word);if(!wk||wk===tw||seenW.has(wk))continue;seenW.add(wk);const d=normalizeDisplay(display(x,mode));if(!d||d===td)continue;const sp=ppos(x.pos)&&ppos(x.pos)===ppos(item.pos),st=shared(x,item);c.push({x,d,tier:sp&&st?0:sp?1:st?2:3});}const out=[],used=new Set([td]);for(let t=0;t<=3&&out.length<count;t++){for(const r of fisherYates(c.filter(x=>x.tier===t),rng)){if(used.has(r.d))continue;used.add(r.d);out.push(r.x);if(out.length===count)break;}}return out;}
export function buildChoices(item,vocab,mode='envi',rng=Math.random){return fisherYates([item,...selectDistractors(item,vocab,mode,3,rng)],rng);}
export function normalizeTypedAnswer(v){return keyOf(v).replace(/[’‘]/g,"'");}
export function typingIsCorrect(v,item){const a=normalizeTypedAnswer(v),b=normalizeTypedAnswer(item.word);return a===b||a.replace(/[-\s]/g,'')===b.replace(/[-\s]/g,'');}
