import { APP_VERSION, STATE_SCHEMA_VERSION, STORAGE_KEY } from './config.js';
import { keyOf, localDateString, addDaysString, safeJsonParse } from './utils.js';
import { applySrsAnswer } from './srs.js';
export function defaultState(){return {schemaVersion:STATE_SCHEMA_VERSION,appVersion:APP_VERSION,selectedStage:1,selectedTopicId:1,browseMode:'topic',sessionSize:10,mode:'adaptive',wrong:{},seen:{},lexCache:{},adaptive:{},srs:{},stats:{lastStudyDate:'',streak:0,totalAnswers:0,todayDate:'',todayAnswers:0,todayCorrect:0},dark:false};}
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
export function migrateState(input,today=localDateString()){const raw=obj(input),state={...defaultState(),...raw};state.wrong=obj(raw.wrong);state.seen=obj(raw.seen);state.lexCache=obj(raw.lexCache);state.adaptive=obj(raw.adaptive);state.srs=obj(raw.srs);state.stats={...defaultState().stats,...obj(raw.stats)};if(Array.isArray(raw.mastered)){for(const word of raw.mastered){const k=keyOf(word);if(!k)continue;const e=state.srs[k]||{};state.srs[k]={box:Math.max(4,e.box||0),due:e.due||addDaysString(today,14),correct:Math.max(2,e.correct||0),wrong:e.wrong||0,last:e.last||today};}}delete state.mastered;delete state.selectedLevel;delete state.meaningCache;delete state.pronCache;delete state.exampleViCache;state.schemaVersion=STATE_SCHEMA_VERSION;state.appVersion=APP_VERSION;if(!['topic','stage'].includes(state.browseMode))state.browseMode='topic';if(!['adaptive','envi','vien','listen'].includes(state.mode))state.mode='adaptive';if(![10,20,30].includes(Number(state.sessionSize)))state.sessionSize=10;return state;}
export function loadState(storage=globalThis.localStorage){let raw=null;try{raw=safeJsonParse(storage?.getItem?.(STORAGE_KEY),null);}catch{}return migrateState(raw);}
export function saveState(state,storage=globalThis.localStorage){try{storage?.setItem?.(STORAGE_KEY,JSON.stringify(state));return true;}catch{return false;}}
export function ensureTodayStats(state,today=localDateString()){if(state.stats.todayDate!==today){state.stats.todayDate=today;state.stats.todayAnswers=0;state.stats.todayCorrect=0;}}
export function registerStudyDay(state,today=localDateString()){ensureTodayStats(state,today);if(state.stats.lastStudyDate===today)return;const yesterday=addDaysString(today,-1);state.stats.streak=state.stats.lastStudyDate===yesterday?(state.stats.streak||0)+1:1;state.stats.lastStudyDate=today;}
export function ensureAdaptiveRecord(state,word){const k=keyOf(word);state.adaptive[k]||={streak:0,totalCorrect:0,totalWrong:0,lastMode:'',lastResult:'',lastAt:0,byMode:{envi:{c:0,w:0},vien:{c:0,w:0},listen:{c:0,w:0},type:{c:0,w:0}}};return state.adaptive[k];}
export function applyLearningAnswer(state,item,isCorrect,quizMode,today=localDateString()){const k=keyOf(item.word);registerStudyDay(state,today);const card=applySrsAnswer(state.srs[k],isCorrect,today);state.srs[k]=card;state.wrong[k]=Math.max(0,(state.wrong[k]||0)+(isCorrect?-1:1));state.seen[k]=(state.seen[k]||0)+1;const a=ensureAdaptiveRecord(state,item.word);a.byMode[quizMode]||={c:0,w:0};if(isCorrect){a.streak=(a.streak||0)+1;a.totalCorrect=(a.totalCorrect||0)+1;a.byMode[quizMode].c++;}else{a.streak=0;a.totalWrong=(a.totalWrong||0)+1;a.byMode[quizMode].w++;}a.lastMode=quizMode;a.lastResult=isCorrect?'correct':'wrong';a.lastAt=Date.now();state.stats.totalAnswers=(state.stats.totalAnswers||0)+1;state.stats.todayAnswers=(state.stats.todayAnswers||0)+1;if(isCorrect)state.stats.todayCorrect=(state.stats.todayCorrect||0)+1;return card;}
